### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [dstructs/typed-array-to-json#1]

**Comment by Planeshifter** [comment]
Removed a console.log from the README.md file, otherwise all looks good to me. Publish?

**Comment by kgryte** [comment]
Thanks for the edit and looking it over! Will publish later tonight or tomorrow.

**Comment by Planeshifter** [comment]
Was so free to land this module on npm after updating the `type-name` dependency. All tests pass locally, but on _travis-io_ we get  the same error message for node `v5.0.0` as for the `math-io` modules.

**Comment by kgryte** [comment]
Thanks. Had totally forgotten to do this. And yeah, we are going to have to go through and rerun all the `travis` builds once NPM fixes its bug.
